url: http://mroach.com
title: mroach.com
excerpt_separator: <!--more-->
markdown: kramdown
exclude: [vendor]
future: true
lang: en
timezone: UTC
repository: mroach/mroach.github.io

remote_theme: yous/whiteglass

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 10

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# sass:
#   sass_dir: _sass
#   style: compressed
